project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
    - "!data/"
  resources:
    - "slides/"
    - "img/"
    - "data/"

website:
  title: "SQMB"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: assessments.qmd
        text: Assessment

format:
  html:
    theme: united
    css: styles.css
    toc: true
    df-print: paged

callout-icon: false

